version: '3'

services:

  mc-mysql:
    image: mysql
    container_name: mc-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "mc"
    volumes:
      - mc-mysql:/var/lib/mysql
    networks:
      - mc

  mc-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "mc-rabbitmq"
    hostname: "rabbitmq.local"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "agaeq14"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5672"
    networks:
      - mc

networks:

  mc:

volumes:
  mc-mysql:
