version: '3'

services:

  sp-haproxy:
    container_name: sp-haproxy
    build: .
    ports:
      - 18080:80
    networks:

      sp:

        ipv4_address: 66.0.0.10

networks:

  sp:

    external: true
